import SuperAdminsComp from '@/components/authors/superAdmins';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Super Admins - Project Management Dashboard',
  description: 'Generated by create next app',
};

export default function Teams() {
  return <SuperAdminsComp />;
}
