import ForgetPassword from '@/components/auth/PasswordsForm/ForgetPassword';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Forget Password - Project Management Dashboard',
  description: 'Generated by create next app',
};

export default function ForgotPassword() {
  return <ForgetPassword />;
}
