import SettingsProfile from '@/components/settings';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Settings - Project Management Dashboard',
  description: 'Generated by create next app',
};

export default function Settings() {
  return <SettingsProfile />;
}
