import ReusablePriority from '@/components/priority';
import { Priority } from '@/state/types';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Urgent Priority - Project Management Dashboard',
  description: 'Generated by create next app',
};

export default function Urgent() {
  return <ReusablePriority priority={Priority.Urgent} />;
}
