import ReusablePriority from '@/components/priority/ReusablePriority';
import { Priority } from '@/state/types';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Urgent Priority - Project Management Dashboard',
  description: 'Generated by create next app',
};

const Urgent = () => {
  return <ReusablePriority priority={Priority.Urgent} />;
};

export default Urgent;
