import EmailVerifyComp from '@/components/auth/EmailVerify/EmailVerifyComp';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: 'Verify Email - Project Management Dashboard',
  description: 'Generated by create next app',
};

const VerifyEmailPage: React.FC = () => {
  return <EmailVerifyComp />;
};

export default VerifyEmailPage;
