import EmailVerifyComp from '@/components/auth/EmailVerify';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Verify Email - Project Management Dashboard',
  description: 'Generated by create next app',
};

export default function VerifyEmailPage() {
  return <EmailVerifyComp />;
}
