import TimelineComp from '@/components/timeline';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Timeline - Project Management Dashboard',
  description: 'Generated by create next app',
};

export default function Timeline() {
  return <TimelineComp />;
}
