import UsersComp from '@/components/users';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Users - Project Management Dashboard',
  description: 'Generated by create next app',
};

export default function Users() {
  return <UsersComp />;
}
