import TeamsComp from '@/components/teams/TeamsComp';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Teams - Project Management Dashboard',
  description: 'Generated by create next app',
};

const Teams = () => {
  return <TeamsComp />;
};

export default Teams;
