import TeamsComp from '@/components/teams';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Teams - Project Management Dashboard',
  description: 'Generated by create next app',
};

export default function Teams() {
  return <TeamsComp />;
}
