import ReusablePriority from '@/_components/priority/ReusablePriority';
import { Priority } from '@/state/types';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Backlog Priority - Project Management Dashboard',
  description: 'Generated by create next app',
};

const Backlog = () => {
  return <ReusablePriority priority={Priority.Backlog} />;
};

export default Backlog;
