import ResetPassword from '@/components/auth/PasswordsForm/ResetPassword';

import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Reset Password - Project Management Dashboard',
  description: 'Generated by create next app',
};

export default function ResetPasswordPage() {
  return <ResetPassword />;
}
