import ReusablePriority from '@/components/priority';
import { Priority } from '@/state/types';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'High Priority - Project Management Dashboard',
  description: 'Generated by create next app',
};

export default function High() {
  return <ReusablePriority priority={Priority.High} />;
}
