import ReusablePriority from '@/components/priority/ReusablePriority';
import { Priority } from '@/state/types';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'High Priority - Project Management Dashboard',
  description: 'Generated by create next app',
};

const High = () => {
  return <ReusablePriority priority={Priority.High} />;
};

export default High;
