import InitializeAuth from '@/components/layout/InitializeAuth';
import StoreProvider from '@/store';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Project Management Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body suppressHydrationWarning className={inter.className}>
        <StoreProvider>
          <InitializeAuth>{children}</InitializeAuth>
        </StoreProvider>
      </body>
    </html>
  );
}
