import InitializeAuth from '@/components/layout/InitializeAuth';
import StoreProvider from '@/store';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Project Management Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body suppressHydrationWarning className={inter.className}>
        <StoreProvider>
          <InitializeAuth>{children}</InitializeAuth>
        </StoreProvider>

        <Toaster
          position='top-right'
          reverseOrder={true}
          toastOptions={{
            // Define default options
            duration: 10000,
            removeDelay: 1000,
          }}
        />
      </body>
    </html>
  );
}
