import TimelineComp from '@/_components/timeline/TimelineComp';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Timeline - Project Management Dashboard',
  description: 'Generated by create next app',
};

const Timeline = () => {
  return <TimelineComp />;
};

export default Timeline;
