import ReusablePriority from '@/components/priority';
import { Priority } from '@/state/types';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Backlog Priority - Project Management Dashboard',
  description: 'Generated by create next app',
};

export default function Backlog() {
  return <ReusablePriority priority={Priority.Backlog} />;
}
