import SearchComp from '@/components/search';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Search - Project Management Dashboard',
  description: 'Generated by create next app',
};

export default function Search() {
  return <SearchComp />;
}
