import ManagersComp from '@/components/authors/managers';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Managers - Project Management Dashboard',
  description: 'Generated by create next app',
};

export default function Teams() {
  return <ManagersComp />;
}
