import SettingsProfile from '@/_components/settings/SettingsProfile';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Settings - Project Management Dashboard',
  description: 'Generated by create next app',
};

const Settings = () => {
  return <SettingsProfile />;
};

export default Settings;
