import AdminsComp from '@/components/authors/admins';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Admins - Project Management Dashboard',
  description: 'Generated by create next app',
};

export default function Teams() {
  return <AdminsComp />;
}
