import ReusablePriority from '@/components/priority/ReusablePriority';
import { Priority } from '@/state/types';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Low Priority - Project Management Dashboard',
  description: 'Generated by create next app',
};

const Low = () => {
  return <ReusablePriority priority={Priority.Low} />;
};

export default Low;
