import ReusablePriority from '@/components/priority/ReusablePriority';
import { Priority } from '@/state/types';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Medium Priority - Project Management Dashboard',
  description: 'Generated by create next app',
};

const Medium = () => {
  return <ReusablePriority priority={Priority.Medium} />;
};

export default Medium;
