import DevelopersComp from '@/components/authors/developers';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Developers - Project Management Dashboard',
  description: 'Generated by create next app',
};

export default function Teams() {
  return <DevelopersComp />;
}
