import ProjectsComp from '@/components/projects/ProjectsComp';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Projects - Project Management Dashboard',
  description: 'Generated by create next app',
};

const Projects = () => {
  return <ProjectsComp />;
};

export default Projects;
