import ProjectsComp from '@/components/projects';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Projects - Project Management Dashboard',
  description: 'Generated by create next app',
};

export default function Projects() {
  return <ProjectsComp />;
}
